package org.itri.ccma.tarsan.hibernate;
// Generated Sep 3, 2015 11:03:17 AM by Hibernate Tools 4.3.1
import com.fasterxml.jackson.annotation.JsonIgnore;import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ad generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "ad")
public class Ad implements java.io.Serializable {

	private long adId;
	private Long adGroup;
	private String keywords;
	private String url;
	private String img;
	private String domain;
	private int shownTimes;
	private int clickedTimes;
	private int closedTimes;
	private float weight;
	private Date expireDateTime;
	private Date createdDateTime;
	private boolean expiredFlag;
	private boolean deletedFlag;
	private Set<Ad2user> ad2users = new HashSet<Ad2user>(0);
	private Set<Pattern2ad> pattern2ads = new HashSet<Pattern2ad>(0);

	public Ad() {
	}

	public Ad(long adId, int shownTimes, int clickedTimes, int closedTimes, float weight, Date createdDateTime,
			boolean expiredFlag, boolean deletedFlag) {
		this.adId = adId;
		this.shownTimes = shownTimes;
		this.clickedTimes = clickedTimes;
		this.closedTimes = closedTimes;
		this.weight = weight;
		this.createdDateTime = createdDateTime;
		this.expiredFlag = expiredFlag;
		this.deletedFlag = deletedFlag;
	}

	public Ad(long adId, Long adGroup, String keywords, String url, String img, String domain, int shownTimes,
			int clickedTimes, int closedTimes, float weight, Date expireDateTime, Date createdDateTime,
			boolean expiredFlag, boolean deletedFlag, Set<Ad2user> ad2users, Set<Pattern2ad> pattern2ads) {
		this.adId = adId;
		this.adGroup = adGroup;
		this.keywords = keywords;
		this.url = url;
		this.img = img;
		this.domain = domain;
		this.shownTimes = shownTimes;
		this.clickedTimes = clickedTimes;
		this.closedTimes = closedTimes;
		this.weight = weight;
		this.expireDateTime = expireDateTime;
		this.createdDateTime = createdDateTime;
		this.expiredFlag = expiredFlag;
		this.deletedFlag = deletedFlag;
		this.ad2users = ad2users;
		this.pattern2ads = pattern2ads;
	}

	@SequenceGenerator(name="ad_seq", sequenceName="ad_ad_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ad_seq")	@Id

	@Column(name = "ad_id", unique = true, nullable = false)
	public long getAdId() {
		return this.adId;
	}

	public void setAdId(long adId) {
		this.adId = adId;
	}

	@Column(name = "ad_group")
	public Long getAdGroup() {
		return this.adGroup;
	}

	public void setAdGroup(Long adGroup) {
		this.adGroup = adGroup;
	}

	@Column(name = "keywords", length = 128)
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@Column(name = "url", length = 2048)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "img", length = 2048)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Column(name = "domain", length = 128)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "shown_times", nullable = false)
	public int getShownTimes() {
		return this.shownTimes;
	}

	public void setShownTimes(int shownTimes) {
		this.shownTimes = shownTimes;
	}

	@Column(name = "clicked_times", nullable = false)
	public int getClickedTimes() {
		return this.clickedTimes;
	}

	public void setClickedTimes(int clickedTimes) {
		this.clickedTimes = clickedTimes;
	}

	@Column(name = "closed_times", nullable = false)
	public int getClosedTimes() {
		return this.closedTimes;
	}

	public void setClosedTimes(int closedTimes) {
		this.closedTimes = closedTimes;
	}

	@Column(name = "weight", nullable = false, precision = 8, scale = 8)
	public float getWeight() {
		return this.weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_date_time", length = 29)
	public Date getExpireDateTime() {
		return this.expireDateTime;
	}

	public void setExpireDateTime(Date expireDateTime) {
		this.expireDateTime = expireDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date_time", nullable = false, length = 29)
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "expired_flag", nullable = false)
	public boolean isExpiredFlag() {
		return this.expiredFlag;
	}

	public void setExpiredFlag(boolean expiredFlag) {
		this.expiredFlag = expiredFlag;
	}

	@Column(name = "deleted_flag", nullable = false)
	public boolean isDeletedFlag() {
		return this.deletedFlag;
	}

	public void setDeletedFlag(boolean deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ad")
	@JsonIgnore	public Set<Ad2user> getAd2users() {
		return this.ad2users;
	}

	public void setAd2users(Set<Ad2user> ad2users) {
		this.ad2users = ad2users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ad")
	@JsonIgnore	public Set<Pattern2ad> getPattern2ads() {
		return this.pattern2ads;
	}

	public void setPattern2ads(Set<Pattern2ad> pattern2ads) {
		this.pattern2ads = pattern2ads;
	}

}
