package org.itri.ccma.tarsan.hibernate;
// Generated Sep 3, 2015 11:03:17 AM by Hibernate Tools 4.3.1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdGroup generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "ad_group")
public class AdGroup implements java.io.Serializable {

	private long adGroupId;

	public AdGroup() {
	}

	public AdGroup(long adGroupId) {
		this.adGroupId = adGroupId;
	}

	@SequenceGenerator(name="ad_group_seq", sequenceName="ad_group_ad_group_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="ad_group_seq")	@Id

	@Column(name = "ad_group_id", unique = true, nullable = false)
	public long getAdGroupId() {
		return this.adGroupId;
	}

	public void setAdGroupId(long adGroupId) {
		this.adGroupId = adGroupId;
	}

}
