package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Adkeyword generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "adkeyword", schema = "public")
public class Adkeyword implements java.io.Serializable {

	private long adkId;
	private Buyad buyad;
	private String adKeyword;

	public Adkeyword() {
	}

	public Adkeyword(long adkId, Buyad buyad) {
		this.adkId = adkId;
		this.buyad = buyad;
	}

	public Adkeyword(long adkId, Buyad buyad, String adKeyword) {
		this.adkId = adkId;
		this.buyad = buyad;
		this.adKeyword = adKeyword;
	}

	@SequenceGenerator(name="adkeyword_seq", sequenceName="adkeyword_adkeyword_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="adkeyword_seq")	@Id
	@Column(name = "adk_id", unique = true, nullable = false)
	public long getAdkId() {
		return this.adkId;
	}

	public void setAdkId(long adkId) {
		this.adkId = adkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buyad_id", nullable = false)
	public Buyad getBuyad() {
		return this.buyad;
	}

	public void setBuyad(Buyad buyad) {
		this.buyad = buyad;
	}

	@Column(name = "ad_keyword", length = 128)
	public String getAdKeyword() {
		return this.adKeyword;
	}

	public void setAdKeyword(String adKeyword) {
		this.adKeyword = adKeyword;
	}

}
