package org.itri.ccma.tarsan.hibernate;
// default package
// Generated 2015/12/7 �U�� 03:35:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Barcode generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "barcode")
public class Barcode implements java.io.Serializable {

	private long barcodeId;
	private String shop;

	public Barcode() {
	}

	public Barcode(long barcodeId) {
		this.barcodeId = barcodeId;
	}

	public Barcode(long barcodeId, String shop) {
		this.barcodeId = barcodeId;
		this.shop = shop;
	}
//	@SequenceGenerator(name="barcode_seq", sequenceName="barcode_barcode_id_seq", allocationSize=1)
//	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="barcode_seq")
	@Id
	@Column(name = "barcode_id", unique = true, nullable = false)
	public long getBarcodeId() {
		return this.barcodeId;
	}

	public void setBarcodeId(long barcodeId) {
		this.barcodeId = barcodeId;
	}

	@Column(name = "shop", length = 128)
	public String getShop() {
		return this.shop;
	}

	public void setShop(String shop) {
		this.shop = shop;
	}

}
