package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Budgetpool generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "budgetpool", schema = "public")
public class Budgetpool implements java.io.Serializable {

	private long budgetId;
	private Buyad buyad;
	private Long budgetNum;
	private String budgetUnit;
	private Long budgetCount;
	private Long budgetTotal;
	private Date createdate;
	private Date updatetime;
	private Set<Budgetlog> budgetlogs = new HashSet<Budgetlog>(0);

	public Budgetpool() {
	}

	public Budgetpool(long budgetId) {
		this.budgetId = budgetId;
	}

	public Budgetpool(long budgetId, Buyad buyad, Long budgetNum,
			String budgetUnit, Long budgetCount, Long budgetTotal,
			Date createdate, Date updatetime, Set <Budgetlog>budgetlogs) {
		this.budgetId = budgetId;
		this.buyad = buyad;
		this.budgetNum = budgetNum;
		this.budgetUnit = budgetUnit;
		this.budgetCount = budgetCount;
		this.budgetTotal = budgetTotal;
		this.createdate = createdate;
		this.updatetime = updatetime;
		this.budgetlogs = budgetlogs;
	}

	@SequenceGenerator(name="budgetpool_seq", sequenceName="budgetpool_budgetpool_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="budgetpool_seq")	@Id
	@Column(name = "budget_id", unique = true, nullable = false)
	public long getBudgetId() {
		return this.budgetId;
	}

	public void setBudgetId(long budgetId) {
		this.budgetId = budgetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buyad_id")
	public Buyad getBuyad() {
		return this.buyad;
	}

	public void setBuyad(Buyad buyad) {
		this.buyad = buyad;
	}

	@Column(name = "budget_num")
	public Long getBudgetNum() {
		return this.budgetNum;
	}

	public void setBudgetNum(Long budgetNum) {
		this.budgetNum = budgetNum;
	}

	@Column(name = "budget_unit", length = 128)
	public String getBudgetUnit() {
		return this.budgetUnit;
	}

	public void setBudgetUnit(String budgetUnit) {
		this.budgetUnit = budgetUnit;
	}

	@Column(name = "budget_count")
	public Long getBudgetCount() {
		return this.budgetCount;
	}

	public void setBudgetCount(Long budgetCount) {
		this.budgetCount = budgetCount;
	}

	@Column(name = "budget_total")
	public Long getBudgetTotal() {
		return this.budgetTotal;
	}

	public void setBudgetTotal(Long budgetTotal) {
		this.budgetTotal = budgetTotal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 29)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 29)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "budgetpool")
	public Set <Budgetlog>getBudgetlogs() {
		return this.budgetlogs;
	}

	public void setBudgetlogs(Set <Budgetlog>budgetlogs) {
		this.budgetlogs = budgetlogs;
	}

}
