package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Buyad generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "buyad", schema = "public")
public class Buyad implements java.io.Serializable {

	private long buyadId;
	private Vacantad vacantad;
	private Exuser exuser;
	private Long postadId;
	private String title;
	private String type;
	private String content;
	private String position;
	private String size;
	private String price;
	private Date startdate;
	private Date enddate;
	private String intervaltime;
	private Boolean posted;
	private Date createdate;
	private Date updatetime;
	private Boolean del;
	private Set <Postad>postads = new HashSet<Postad>(0);
	private Set <Budgetpool>budgetpools = new HashSet<Budgetpool>(0);
	private Set <Buyad2loc>buyad2locs = new HashSet<Buyad2loc>(0);
	private Set <Adkeyword>adkeywords = new HashSet<Adkeyword>(0);

	public Buyad() {
	}

	public Buyad(long buyadId, Date createdate) {
		this.buyadId = buyadId;
		this.createdate = createdate;
	}

	public Buyad(long buyadId, Vacantad vacantad, Exuser exuser, Long postadId,
			String title, String type, String content, String position,
			String size, String price, Date startdate, Date enddate,
			String intervaltime, Boolean posted, Date createdate,
			Date updatetime, Boolean del, Set <Postad>postads, Set<Budgetpool> budgetpools,
			Set <Buyad2loc>buyad2locs, Set <Adkeyword>adkeywords) {
		this.buyadId = buyadId;
		this.vacantad = vacantad;
		this.exuser = exuser;
		this.postadId = postadId;
		this.title = title;
		this.type = type;
		this.content = content;
		this.position = position;
		this.size = size;
		this.price = price;
		this.startdate = startdate;
		this.enddate = enddate;
		this.intervaltime = intervaltime;
		this.posted = posted;
		this.createdate = createdate;
		this.updatetime = updatetime;
		this.del = del;
		this.postads = postads;
		this.budgetpools = budgetpools;
		this.buyad2locs = buyad2locs;
		this.adkeywords = adkeywords;
	}

	@SequenceGenerator(name="buyad_seq", sequenceName="buyad_buyad_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="buyad_seq")	@Id
	@Column(name = "buyad_id", unique = true, nullable = false)
	public long getBuyadId() {
		return this.buyadId;
	}

	public void setBuyadId(long buyadId) {
		this.buyadId = buyadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vacant_id")
	public Vacantad getVacantad() {
		return this.vacantad;
	}

	public void setVacantad(Vacantad vacantad) {
		this.vacantad = vacantad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exuser_id")
	public Exuser getExuser() {
		return this.exuser;
	}

	public void setExuser(Exuser exuser) {
		this.exuser = exuser;
	}

	@Column(name = "postad_id")
	public Long getPostadId() {
		return this.postadId;
	}

	public void setPostadId(Long postadId) {
		this.postadId = postadId;
	}

	@Column(name = "title", length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "type", length = 128)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "position", length = 128)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "size", length = 128)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "price", length = 128)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdate", length = 29)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enddate", length = 29)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "intervaltime", length = 128)
	public String getIntervaltime() {
		return this.intervaltime;
	}

	public void setIntervaltime(String intervaltime) {
		this.intervaltime = intervaltime;
	}

	@Column(name = "posted")
	public Boolean getPosted() {
		return this.posted;
	}

	public void setPosted(Boolean posted) {
		this.posted = posted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 29)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 29)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "del")
	public Boolean getDel() {
		return this.del;
	}

	public void setDel(Boolean del) {
		this.del = del;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyad")
	public Set <Postad>getPostads() {
		return this.postads;
	}

	public void setPostads(Set <Postad>postads) {
		this.postads = postads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyad")
	public Set <Budgetpool>getBudgetpools() {
		return this.budgetpools;
	}

	public void setBudgetpools(Set <Budgetpool>budgetpools) {
		this.budgetpools = budgetpools;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyad")
	public Set <Buyad2loc>getBuyad2locs() {
		return this.buyad2locs;
	}

	public void setBuyad2locs(Set <Buyad2loc>buyad2locs) {
		this.buyad2locs = buyad2locs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyad")
	public Set <Adkeyword>getAdkeywords() {
		return this.adkeywords;
	}

	public void setAdkeywords(Set <Adkeyword>adkeywords) {
		this.adkeywords = adkeywords;
	}

}
