package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Buyad2loc generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "buyad2loc", schema = "public")
public class Buyad2loc implements java.io.Serializable {

	private long ad2locId;
	private Buyad buyad;
	private Location location;

	public Buyad2loc() {
	}

	public Buyad2loc(long ad2locId) {
		this.ad2locId = ad2locId;
	}

	public Buyad2loc(long ad2locId, Buyad buyad, Location location) {
		this.ad2locId = ad2locId;
		this.buyad = buyad;
		this.location = location;
	}

	@SequenceGenerator(name="buyad2loc_seq", sequenceName="buyad2loc_buyad2loc_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="buyad2loc_seq")	@Id
	@Column(name = "ad2loc_id", unique = true, nullable = false)
	public long getAd2locId() {
		return this.ad2locId;
	}

	public void setAd2locId(long ad2locId) {
		this.ad2locId = ad2locId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buyad_id")
	public Buyad getBuyad() {
		return this.buyad;
	}

	public void setBuyad(Buyad buyad) {
		this.buyad = buyad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loc_id")
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

}
