package org.itri.ccma.tarsan.hibernate;

// Generated 2016/7/27 ¤U¤È 04:40:34 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConnectLog generated by hbm2java
 */

@SuppressWarnings("serial")@Entity
@Table(name = "connect_log", schema = "public")
public class ConnectLog implements java.io.Serializable {

	private long connectLogId;
	private String ip;
	private String deviceType;
	private String os;
	private String browser;
	private String brand;
	private String mac;
	private String ssid;
	private String machine;
	private String url;
	private Date createdate;

	public ConnectLog() {
	}

	public ConnectLog(long connectLogId, Date createdate) {
		this.connectLogId = connectLogId;
		this.createdate = createdate;
	}

	public ConnectLog(long connectLogId, String ip, String deviceType,
			String os, String browser, String brand, String mac, String ssid,
			String machine, String url, Date createdate) {
		this.connectLogId = connectLogId;
		this.ip = ip;
		this.deviceType = deviceType;
		this.os = os;
		this.browser = browser;
		this.brand = brand;
		this.mac = mac;
		this.ssid = ssid;
		this.machine = machine;
		this.url = url;
		this.createdate = createdate;
	}
	@SequenceGenerator(name="connect_log_seq", sequenceName="connect_log_connect_log_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="connect_log_seq")	@Id
	@Column(name = "connect_log_id", unique = true, nullable = false)
	public long getConnectLogId() {
		return this.connectLogId;
	}

	public void setConnectLogId(long connectLogId) {
		this.connectLogId = connectLogId;
	}
	@Column(name = "ip", length = 39)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
	@Column(name = "device_type", length = 256)
	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}
	@Column(name = "os", length = 256)
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}
	@Column(name="browser", length=256)
	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}
	@Column(name="brand", length=256)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}
	@Column(name="mac", length=17)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}
	@Column(name="ssid", length=256)
	public String getSsid() {
		return this.ssid;
	}

	public void setSsid(String ssid) {
		this.ssid = ssid;
	}
	@Column(name="machine", length=128)
	public String getMachine() {
		return this.machine;
	}

	public void setMachine(String machine) {
		this.machine = machine;
	}
	@Column(name="url", length=65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="createdate",nullable = false, length=29)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
