package org.itri.ccma.tarsan.hibernate;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
// Generated 2016/6/16 ¤U¤È 03:38:46 by Hibernate Tools 3.4.0.CR1
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Control generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "control")
public class Control implements java.io.Serializable {

	private long controlId;
	private String userId;
	private String macAddr;
	private String pageUrl;
	private String sessionTime;
	private String owner;
	private String uploadFile;
	private String uploadType;
	private Date lastActiveTime;

	public Control() {
	}

	public Control(long controlId) {
		this.controlId = controlId;
	}

	public Control(long controlId, String userId, String macAddr,
			String pageUrl, String sessionTime, String owner,
			String uploadFile, String uploadType, Date lastActiveTime) {
		this.controlId = controlId;
		this.userId = userId;
		this.macAddr = macAddr;
		this.pageUrl = pageUrl;
		this.sessionTime = sessionTime;
		this.owner = owner;
		this.uploadFile = uploadFile;
		this.uploadType = uploadType;
		this.lastActiveTime = lastActiveTime;
	}
	@SequenceGenerator(name="control_seq", sequenceName="control_control_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="control_seq")
	@Id

	@Column(name = "control_id", unique = true, nullable = false)
	public long getControlId() {
		return this.controlId;
	}

	public void setControlId(long controlId) {
		this.controlId = controlId;
	}
	@Column(name = "user_id", length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	@Column(name = "mac_addr", length = 12)
	public String getMacAddr() {
		return this.macAddr;
	}

	public void setMacAddr(String macAddr) {
		this.macAddr = macAddr;
	}
	@Column(name = "page_url", length = 65535)
	public String getPageUrl() {
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}
	@Column(name = "session_time", length = 5)
	public String getSessionTime() {
		return this.sessionTime;
	}

	public void setSessionTime(String sessionTime) {
		this.sessionTime = sessionTime;
	}
	@Column(name = "owner", length = 128)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}
	@Column(name = "upload_file", length = 256)
	public String getUploadFile() {
		return this.uploadFile;
	}

	public void setUploadFile(String uploadFile) {
		this.uploadFile = uploadFile;
	}
	@Column(name = "upload_type", length = 256)
	public String getUploadType() {
		return this.uploadType;
	}

	public void setUploadType(String uploadType) {
		this.uploadType = uploadType;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_active_time", length = 29)
	public Date getLastActiveTime() {
		return this.lastActiveTime;
	}

	public void setLastActiveTime(Date lastActiveTime) {
		this.lastActiveTime = lastActiveTime;
	}

}
