package org.itri.ccma.tarsan.hibernate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
// Generated 2016/6/16 ¤U¤È 03:38:46 by Hibernate Tools 3.4.0.CR1

/**
 * Control generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "control")
public class Control implements java.io.Serializable {

	private long controlId;
	private String userId;
	private String macAddr;
	private String pageUrl;

	public Control() {
	}

	public Control(long controlId) {
		this.controlId = controlId;
	}

	public Control(long controlId, String userId, String macAddr, String pageUrl) {
		this.controlId = controlId;
		this.userId = userId;
		this.macAddr = macAddr;
		this.pageUrl = pageUrl;
	}
	@SequenceGenerator(name="control_seq", sequenceName="control_control_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="control_seq")
	@Id

	@Column(name = "control_id", unique = true, nullable = false)
	public long getControlId() {
		return this.controlId;
	}

	public void setControlId(long controlId) {
		this.controlId = controlId;
	}
	@Column(name = "user_id", length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	@Column(name = "mac_addr", length = 12)
	public String getMacAddr() {
		return this.macAddr;
	}

	public void setMacAddr(String macAddr) {
		this.macAddr = macAddr;
	}
	@Column(name = "page_url", length = 65535)
	public String getPageUrl() {
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

}
