package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Denykeyword generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "denykeyword", schema = "public")
public class Denykeyword implements java.io.Serializable {

	private long dkId;
	private String DKeyword;

	public Denykeyword() {
	}

	public Denykeyword(long dkId) {
		this.dkId = dkId;
	}

	public Denykeyword(long dkId, String DKeyword) {
		this.dkId = dkId;
		this.DKeyword = DKeyword;
	}

	@SequenceGenerator(name="denykeyword_seq", sequenceName="denykeyword_denykeyword_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="denykeyword_seq")	@Id
	@Column(name = "dk_id", unique = true, nullable = false)
	public long getDkId() {
		return this.dkId;
	}

	public void setDkId(long dkId) {
		this.dkId = dkId;
	}

	@Column(name = "d_keyword", length = 128)
	public String getDKeyword() {
		return this.DKeyword;
	}

	public void setDKeyword(String DKeyword) {
		this.DKeyword = DKeyword;
	}

}
