package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exuser generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "exuser", schema = "public")
public class Exuser implements java.io.Serializable {

	private long exuserId;
	private Exusergroup exusergroup;
	private String account;
	private String password;
	private String name;
	private String email;
	private String phone;
	private String address;
	private String company;
	private String timezone;
	private String country;
	private String currency;
	private Date createdate;
	private Date lastlogin;
	private Set <Exuserlog>exuserlogs = new HashSet<Exuserlog>(0);
	private Set <Buyad>buyads = new HashSet<Buyad>(0);
	private Set <Vacantad>vacantads = new HashSet<Vacantad>(0);

	public Exuser() {
	}

	public Exuser(long exuserId) {
		this.exuserId = exuserId;
	}

	public Exuser(long exuserId, Exusergroup exusergroup, String account,
			String password, String name, String email, String phone,
			String address, String company, String timezone, String country,
			String currency, Date createdate, Date lastlogin, Set <Exuserlog>exuserlogs,
			Set <Buyad>buyads, Set <Vacantad>vacantads) {
		this.exuserId = exuserId;
		this.exusergroup = exusergroup;
		this.account = account;
		this.password = password;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.company = company;
		this.timezone = timezone;
		this.country = country;
		this.currency = currency;
		this.createdate = createdate;
		this.lastlogin = lastlogin;
		this.exuserlogs = exuserlogs;
		this.buyads = buyads;
		this.vacantads = vacantads;
	}

	@SequenceGenerator(name="exuser_seq", sequenceName="exuser_exuser_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="exuser_seq")	@Id
	@Column(name = "exuser_id", unique = true, nullable = false)
	public long getExuserId() {
		return this.exuserId;
	}

	public void setExuserId(long exuserId) {
		this.exuserId = exuserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public Exusergroup getExusergroup() {
		return this.exusergroup;
	}

	public void setExusergroup(Exusergroup exusergroup) {
		this.exusergroup = exusergroup;
	}

	@Column(name = "account", length = 128)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "password", length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address", length = 128)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "company", length = 128)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "timezone", length = 128)
	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	@Column(name = "country", length = 128)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "currency", length = 128)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 29)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastlogin", length = 29)
	public Date getLastlogin() {
		return this.lastlogin;
	}

	public void setLastlogin(Date lastlogin) {
		this.lastlogin = lastlogin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exuser")
	public Set <Exuserlog>getExuserlogs() {
		return this.exuserlogs;
	}

	public void setExuserlogs(Set <Exuserlog>exuserlogs) {
		this.exuserlogs = exuserlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exuser")
	public Set <Buyad>getBuyads() {
		return this.buyads;
	}

	public void setBuyads(Set <Buyad>buyads) {
		this.buyads = buyads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exuser")
	public Set <Vacantad>getVacantads() {
		return this.vacantads;
	}

	public void setVacantads(Set <Vacantad>vacantads) {
		this.vacantads = vacantads;
	}

}
