package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exusergroup generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "exusergroup", schema = "public")
public class Exusergroup implements java.io.Serializable {

	private long groupId;
	private String remark;
	private Set <Exuser>exusers = new HashSet<Exuser>(0);

	public Exusergroup() {
	}

	public Exusergroup(long groupId) {
		this.groupId = groupId;
	}

	public Exusergroup(long groupId, String remark, Set <Exuser>exusers) {
		this.groupId = groupId;
		this.remark = remark;
		this.exusers = exusers;
	}

	@SequenceGenerator(name="exusergroup_seq", sequenceName="exusergroup_exusergroup_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="exusergroup_seq")	@Id
	@Column(name = "group_id", unique = true, nullable = false)
	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	@Column(name = "remark", length = 128)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exusergroup")
	public Set<Exuser> getExusers() {
		return this.exusers;
	}

	public void setExusers(Set <Exuser>exusers) {
		this.exusers = exusers;
	}

}
