package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exuserlog generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "exuserlog", schema = "public")
public class Exuserlog implements java.io.Serializable {

	private long logId;
	private Exuser exuser;
	private String ip;
	private String activity;
	private Date createdate;

	public Exuserlog() {
	}

	public Exuserlog(long logId, Exuser exuser) {
		this.logId = logId;
		this.exuser = exuser;
	}

	public Exuserlog(long logId, Exuser exuser, String ip, String activity,
			Date createdate) {
		this.logId = logId;
		this.exuser = exuser;
		this.ip = ip;
		this.activity = activity;
		this.createdate = createdate;
	}

	@SequenceGenerator(name="exuserlog_seq", sequenceName="exuserlog_exuserlog_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.IDENTITY, generator="exuserlog_seq")	@Id
	@Column(name = "log_id", unique = true, nullable = false)
	public long getLogId() {
		return this.logId;
	}

	public void setLogId(long logId) {
		this.logId = logId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exuser_id", nullable = false)
	public Exuser getExuser() {
		return this.exuser;
	}

	public void setExuser(Exuser exuser) {
		this.exuser = exuser;
	}

	@Column(name = "ip", length = 128)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "activity", length = 128)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 29)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
