package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/29 �U�� 05:29:39 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logad generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "logad", schema = "public")
public class Logad implements java.io.Serializable {

	private long logadId;
	private Postad postad;
	private String searchKeyword;
	private String domain;
	private String urlhost;
	private String urlreferer;
	private String urlpath;
	private String ip;
	private Boolean show;
	private Boolean click;
	private Date createdate;
	private String hashkey;

	public Logad() {
	}

	public Logad(long logadId, Date createdate) {
		this.logadId = logadId;
		this.createdate = createdate;
	}

	public Logad(long logadId, Postad postad, String searchKeyword,
			String domain, String urlhost, String urlreferer, String urlpath,
			String ip, Boolean show, Boolean click, Date createdate,
			String hashkey) {
		this.logadId = logadId;
		this.postad = postad;
		this.searchKeyword = searchKeyword;
		this.domain = domain;
		this.urlhost = urlhost;
		this.urlreferer = urlreferer;
		this.urlpath = urlpath;
		this.ip = ip;
		this.show = show;
		this.click = click;
		this.createdate = createdate;
		this.hashkey = hashkey;
	}

	@SequenceGenerator(name="logad_seq", sequenceName="logad_logad_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="logad_seq")	@Id
	@Column(name = "logad_id", unique = true, nullable = false)
	public long getLogadId() {
		return this.logadId;
	}

	public void setLogadId(long logadId) {
		this.logadId = logadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "postad_id", referencedColumnName = "postad_id"),
			@JoinColumn(name = "buyad_id", referencedColumnName = "buyad_id") })
	public Postad getPostad() {
		return this.postad;
	}

	public void setPostad(Postad postad) {
		this.postad = postad;
	}

	@Column(name = "search_keyword", length = 128)
	public String getSearchKeyword() {
		return this.searchKeyword;
	}

	public void setSearchKeyword(String searchKeyword) {
		this.searchKeyword = searchKeyword;
	}

	@Column(name = "domain", length = 128)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "urlhost", length = 128)
	public String getUrlhost() {
		return this.urlhost;
	}

	public void setUrlhost(String urlhost) {
		this.urlhost = urlhost;
	}

	@Column(name = "urlreferer", length = 65535)
	public String getUrlreferer() {
		return this.urlreferer;
	}

	public void setUrlreferer(String urlreferer) {
		this.urlreferer = urlreferer;
	}

	@Column(name = "urlpath", length = 65535)
	public String getUrlpath() {
		return this.urlpath;
	}

	public void setUrlpath(String urlpath) {
		this.urlpath = urlpath;
	}

	@Column(name = "ip", length = 128)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "show")
	public Boolean getShow() {
		return this.show;
	}

	public void setShow(Boolean show) {
		this.show = show;
	}

	@Column(name = "click")
	public Boolean getClick() {
		return this.click;
	}

	public void setClick(Boolean click) {
		this.click = click;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 29)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "hashkey", length = 128)
	public String getHashkey() {
		return this.hashkey;
	}

	public void setHashkey(String hashkey) {
		this.hashkey = hashkey;
	}

}
