package org.itri.ccma.tarsan.hibernate;
// Generated Sep 3, 2015 11:03:17 AM by Hibernate Tools 4.3.1
import com.fasterxml.jackson.annotation.JsonIgnore;import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pattern2ad generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "pattern2ad")
public class Pattern2ad implements java.io.Serializable {

	private long pattern2adId;
	private Ad ad;
	private Pattern pattern;

	public Pattern2ad() {
	}

	public Pattern2ad(long pattern2adId, Ad ad, Pattern pattern) {
		this.pattern2adId = pattern2adId;
		this.ad = ad;
		this.pattern = pattern;
	}

	@SequenceGenerator(name="pattern2ad_seq", sequenceName="pattern2ad_pattern2ad_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="pattern2ad_seq")	@Id

	@Column(name = "pattern2ad_id", unique = true, nullable = false)
	public long getPattern2adId() {
		return this.pattern2adId;
	}

	public void setPattern2adId(long pattern2adId) {
		this.pattern2adId = pattern2adId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_id", nullable = false)
	@JsonIgnore	public Ad getAd() {
		return this.ad;
	}

	public void setAd(Ad ad) {
		this.ad = ad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pattern_id", nullable = false)
	@JsonIgnore	public Pattern getPattern() {
		return this.pattern;
	}

	public void setPattern(Pattern pattern) {
		this.pattern = pattern;
	}

}
