package org.itri.ccma.tarsan.hibernate;
// Generated Sep 3, 2015 11:03:17 AM by Hibernate Tools 4.3.1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PatternType generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "pattern_type")
public class PatternType implements java.io.Serializable {

	private long patternTypeId;
	private String name;
	private String remarks;

	public PatternType() {
	}

	public PatternType(long patternTypeId, String name) {
		this.patternTypeId = patternTypeId;
		this.name = name;
	}

	public PatternType(long patternTypeId, String name, String remarks) {
		this.patternTypeId = patternTypeId;
		this.name = name;
		this.remarks = remarks;
	}

	@SequenceGenerator(name="pattern_type_seq", sequenceName="pattern_type_pattern_type_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="pattern_type_seq")	@Id

	@Column(name = "pattern_type_id", unique = true, nullable = false)
	public long getPatternTypeId() {
		return this.patternTypeId;
	}

	public void setPatternTypeId(long patternTypeId) {
		this.patternTypeId = patternTypeId;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "remarks", length = 512)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
