package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PostadId generated by hbm2java
 */
@Embeddable
public class PostadId implements java.io.Serializable {

	private long postadId;
	private long buyadId;

	public PostadId() {
	}

	public PostadId(long postadId, long buyadId) {
		this.postadId = postadId;
		this.buyadId = buyadId;
	}

	@Column(name = "postad_id", nullable = false)
	public long getPostadId() {
		return this.postadId;
	}

	public void setPostadId(long postadId) {
		this.postadId = postadId;
	}

	@Column(name = "buyad_id", nullable = false)
	public long getBuyadId() {
		return this.buyadId;
	}

	public void setBuyadId(long buyadId) {
		this.buyadId = buyadId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PostadId))
			return false;
		PostadId castOther = (PostadId) other;

		return (this.getPostadId() == castOther.getPostadId())
				&& (this.getBuyadId() == castOther.getBuyadId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPostadId();
		result = 37 * result + (int) this.getBuyadId();
		return result;
	}

}
