package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Price generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "price", schema = "public")
public class Price implements java.io.Serializable {

	private long priceId;
	private Vacantad vacantad;
	private String priceNum;
	private String priceUnit;
	private String priceTotal;

	public Price() {
	}

	public Price(long priceId) {
		this.priceId = priceId;
	}

	public Price(long priceId, Vacantad vacantad, String priceNum,
			String priceUnit, String priceTotal) {
		this.priceId = priceId;
		this.vacantad = vacantad;
		this.priceNum = priceNum;
		this.priceUnit = priceUnit;
		this.priceTotal = priceTotal;
	}

	@SequenceGenerator(name="price_seq", sequenceName="price_price_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="price_seq")	@Id
	@Column(name = "price_id", unique = true, nullable = false)
	public long getPriceId() {
		return this.priceId;
	}

	public void setPriceId(long priceId) {
		this.priceId = priceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vacant_id")
	public Vacantad getVacantad() {
		return this.vacantad;
	}

	public void setVacantad(Vacantad vacantad) {
		this.vacantad = vacantad;
	}

	@Column(name = "price_num", length = 128)
	public String getPriceNum() {
		return this.priceNum;
	}

	public void setPriceNum(String priceNum) {
		this.priceNum = priceNum;
	}

	@Column(name = "price_unit", length = 128)
	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	@Column(name = "price_total", length = 128)
	public String getPriceTotal() {
		return this.priceTotal;
	}

	public void setPriceTotal(String priceTotal) {
		this.priceTotal = priceTotal;
	}

}
