package org.itri.ccma.tarsan.hibernate;
// default package
// Generated 2015/12/7 �U�� 03:35:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Record generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "record")
public class Record implements java.io.Serializable {

	private RecordId id;
	private Date recordDateTime;
	private String coordinateX;
	private String coordinateY;

	public Record() {
	}

	public Record(RecordId id) {
		this.id = id;
	}

	public Record(RecordId id, Date recordDateTime, String coordinateX,
			String coordinateY) {
		this.id = id;
		this.recordDateTime = recordDateTime;
		this.coordinateX = coordinateX;
		this.coordinateY = coordinateY;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "usersId", column = @Column(name = "users_id", nullable = false)),
			@AttributeOverride(name = "barcodeId", column = @Column(name = "barcode_id", nullable = false)) })
	public RecordId getId() {
		return this.id;
	}

	public void setId(RecordId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "record_date_time", length = 29)
	public Date getRecordDateTime() {
		return this.recordDateTime;
	}

	public void setRecordDateTime(Date recordDateTime) {
		this.recordDateTime = recordDateTime;
	}

	@Column(name = "coordinate_x", length = 128)
	public String getCoordinateX() {
		return this.coordinateX;
	}

	public void setCoordinateX(String coordinateX) {
		this.coordinateX = coordinateX;
	}

	@Column(name = "coordinate_y", length = 128)
	public String getCoordinateY() {
		return this.coordinateY;
	}

	public void setCoordinateY(String coordinateY) {
		this.coordinateY = coordinateY;
	}

}
