package org.itri.ccma.tarsan.hibernate;
// default package
// Generated 2015/12/7 �U�� 03:35:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecordId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class RecordId implements java.io.Serializable {

	private long usersId;
	private long barcodeId;

	public RecordId() {
	}

	public RecordId(long usersId, long barcodeId) {
		this.usersId = usersId;
		this.barcodeId = barcodeId;
	}

	@Column(name = "users_id", nullable = false)
	public long getUsersId() {
		return this.usersId;
	}

	public void setUsersId(long usersId) {
		this.usersId = usersId;
	}

	@Column(name = "barcode_id", nullable = false)
	public long getBarcodeId() {
		return this.barcodeId;
	}

	public void setBarcodeId(long barcodeId) {
		this.barcodeId = barcodeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecordId))
			return false;
		RecordId castOther = (RecordId) other;

		return (this.getUsersId() == castOther.getUsersId())
				&& (this.getBarcodeId() == castOther.getBarcodeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUsersId();
		result = 37 * result + (int) this.getBarcodeId();
		return result;
	}

}
