package org.itri.ccma.tarsan.hibernate;
// Generated 2016/1/4 �W�� 09:34:05 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReviewPattern generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "review_pattern")
public class ReviewPattern implements java.io.Serializable {

	private long keywordId;
	private String reviewKeyword;

	public ReviewPattern() {
	}

	public ReviewPattern(long keywordId, String reviewKeyword) {
		this.keywordId = keywordId;
		this.reviewKeyword = reviewKeyword;
	}

	@Id
	@Column(name = "keyword_id", unique = true, nullable = false)
	public long getKeywordId() {
		return this.keywordId;
	}

	public void setKeywordId(long keywordId) {
		this.keywordId = keywordId;
	}

	@Column(name = "review_keyword", nullable = false, length = 128)
	public String getReviewKeyword() {
		return this.reviewKeyword;
	}

	public void setReviewKeyword(String reviewKeyword) {
		this.reviewKeyword = reviewKeyword;
	}

}
