package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/10 �W�� 09:36:51 by Hibernate Tools 3.4.0.CR1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rulead generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "rulead", schema = "public")
public class Rulead implements java.io.Serializable {

	private long ruleadId;
	private Long postadId;
	private Long buyadId;
	private String keyword;
	private String domain;
	private String type;
	private String position;
	private String size;
	private String content;
	private Date startdate;
	private Date enddate;
	private String intervaltime;
	private Date createdate;
	private Boolean close;

	public Rulead() {
	}

	public Rulead(long ruleadId) {
		this.ruleadId = ruleadId;
	}

	public Rulead(long ruleadId, Long postadId, Long buyadId, String keyword,
			String domain, String type, String position, String size,
			String content, Date startdate, Date enddate, String intervaltime,
			Date createdate, Boolean close) {
		this.ruleadId = ruleadId;
		this.postadId = postadId;
		this.buyadId = buyadId;
		this.keyword = keyword;
		this.domain = domain;
		this.type = type;
		this.position = position;
		this.size = size;
		this.content = content;
		this.startdate = startdate;
		this.enddate = enddate;
		this.intervaltime = intervaltime;
		this.createdate = createdate;
		this.close = close;
	}

	@SequenceGenerator(name="rulead_seq", sequenceName="rulead_rulead_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="rulead_seq")	@Id
	@Column(name = "rulead_id", unique = true, nullable = false)
	public long getRuleadId() {
		return this.ruleadId;
	}

	public void setRuleadId(long ruleadId) {
		this.ruleadId = ruleadId;
	}

	@Column(name = "postad_id")
	public Long getPostadId() {
		return this.postadId;
	}

	public void setPostadId(Long postadId) {
		this.postadId = postadId;
	}

	@Column(name = "buyad_id")
	public Long getBuyadId() {
		return this.buyadId;
	}

	public void setBuyadId(Long buyadId) {
		this.buyadId = buyadId;
	}

	@Column(name = "keyword", length = 128)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	@Column(name = "domain", length = 128)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "type", length = 128)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "position", length = 128)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "size", length = 128)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "content", length = 128)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdate", length = 29)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enddate", length = 29)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "intervaltime", length = 128)
	public String getIntervaltime() {
		return this.intervaltime;
	}

	public void setIntervaltime(String intervaltime) {
		this.intervaltime = intervaltime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 29)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "close")
	public Boolean getClose() {
		return this.close;
	}

	public void setClose(Boolean close) {
		this.close = close;
	}

}
