package org.itri.ccma.tarsan.hibernate;
// Generated 2016/3/3 �U�� 04:26:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RuleadId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class RuleadId implements java.io.Serializable {

	private String postadId;
	private String buyadId;
	private String keyword;
	private String domain;
	private String type;
	private String position;
	private String size;
	private String content;
	private String startdate;
	private String enddate;
	private String intervaltime;
	private String createdate;
	private String close;

	public RuleadId() {
	}

	public RuleadId(String postadId, String buyadId, String keyword,
			String domain, String type, String position, String size,
			String content, String startdate, String enddate,
			String intervaltime, String createdate, String close) {
		this.postadId = postadId;
		this.buyadId = buyadId;
		this.keyword = keyword;
		this.domain = domain;
		this.type = type;
		this.position = position;
		this.size = size;
		this.content = content;
		this.startdate = startdate;
		this.enddate = enddate;
		this.intervaltime = intervaltime;
		this.createdate = createdate;
		this.close = close;
	}

	@Column(name = "postad_id", length = 10)
	public String getPostadId() {
		return this.postadId;
	}

	public void setPostadId(String postadId) {
		this.postadId = postadId;
	}

	@Column(name = "buyad_id", length = 10)
	public String getBuyadId() {
		return this.buyadId;
	}

	public void setBuyadId(String buyadId) {
		this.buyadId = buyadId;
	}

	@Column(name = "keyword", length = 10)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	@Column(name = "domain", length = 10)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "position", length = 10)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "size", length = 10)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "content", length = 10)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "startdate", length = 10)
	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	@Column(name = "enddate", length = 10)
	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	@Column(name = "intervaltime", length = 10)
	public String getIntervaltime() {
		return this.intervaltime;
	}

	public void setIntervaltime(String intervaltime) {
		this.intervaltime = intervaltime;
	}

	@Column(name = "createdate", length = 10)
	public String getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	@Column(name = "close", length = 10)
	public String getClose() {
		return this.close;
	}

	public void setClose(String close) {
		this.close = close;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RuleadId))
			return false;
		RuleadId castOther = (RuleadId) other;

		return ((this.getPostadId() == castOther.getPostadId()) || (this
				.getPostadId() != null && castOther.getPostadId() != null && this
				.getPostadId().equals(castOther.getPostadId())))
				&& ((this.getBuyadId() == castOther.getBuyadId()) || (this
						.getBuyadId() != null && castOther.getBuyadId() != null && this
						.getBuyadId().equals(castOther.getBuyadId())))
				&& ((this.getKeyword() == castOther.getKeyword()) || (this
						.getKeyword() != null && castOther.getKeyword() != null && this
						.getKeyword().equals(castOther.getKeyword())))
				&& ((this.getDomain() == castOther.getDomain()) || (this
						.getDomain() != null && castOther.getDomain() != null && this
						.getDomain().equals(castOther.getDomain())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())))
				&& ((this.getPosition() == castOther.getPosition()) || (this
						.getPosition() != null
						&& castOther.getPosition() != null && this
						.getPosition().equals(castOther.getPosition())))
				&& ((this.getSize() == castOther.getSize()) || (this.getSize() != null
						&& castOther.getSize() != null && this.getSize()
						.equals(castOther.getSize())))
				&& ((this.getContent() == castOther.getContent()) || (this
						.getContent() != null && castOther.getContent() != null && this
						.getContent().equals(castOther.getContent())))
				&& ((this.getStartdate() == castOther.getStartdate()) || (this
						.getStartdate() != null
						&& castOther.getStartdate() != null && this
						.getStartdate().equals(castOther.getStartdate())))
				&& ((this.getEnddate() == castOther.getEnddate()) || (this
						.getEnddate() != null && castOther.getEnddate() != null && this
						.getEnddate().equals(castOther.getEnddate())))
				&& ((this.getIntervaltime() == castOther.getIntervaltime()) || (this
						.getIntervaltime() != null
						&& castOther.getIntervaltime() != null && this
						.getIntervaltime().equals(castOther.getIntervaltime())))
				&& ((this.getCreatedate() == castOther.getCreatedate()) || (this
						.getCreatedate() != null
						&& castOther.getCreatedate() != null && this
						.getCreatedate().equals(castOther.getCreatedate())))
				&& ((this.getClose() == castOther.getClose()) || (this
						.getClose() != null && castOther.getClose() != null && this
						.getClose().equals(castOther.getClose())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPostadId() == null ? 0 : this.getPostadId().hashCode());
		result = 37 * result
				+ (getBuyadId() == null ? 0 : this.getBuyadId().hashCode());
		result = 37 * result
				+ (getKeyword() == null ? 0 : this.getKeyword().hashCode());
		result = 37 * result
				+ (getDomain() == null ? 0 : this.getDomain().hashCode());
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result
				+ (getPosition() == null ? 0 : this.getPosition().hashCode());
		result = 37 * result
				+ (getSize() == null ? 0 : this.getSize().hashCode());
		result = 37 * result
				+ (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37 * result
				+ (getStartdate() == null ? 0 : this.getStartdate().hashCode());
		result = 37 * result
				+ (getEnddate() == null ? 0 : this.getEnddate().hashCode());
		result = 37
				* result
				+ (getIntervaltime() == null ? 0 : this.getIntervaltime()
						.hashCode());
		result = 37
				* result
				+ (getCreatedate() == null ? 0 : this.getCreatedate()
						.hashCode());
		result = 37 * result
				+ (getClose() == null ? 0 : this.getClose().hashCode());
		return result;
	}

}
