package org.itri.ccma.tarsan.hibernate;

// Generated 2016/3/21 �U�� 01:28:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RunadId generated by hbm2java
 */
@Embeddable
public class RunadId implements java.io.Serializable {

	private long runadId;
	private long postadId;
	private long buyadId;

	public RunadId() {
	}

	public RunadId(long runadId, long postadId, long buyadId) {
		this.runadId = runadId;
		this.postadId = postadId;
		this.buyadId = buyadId;
	}

	@Column(name = "runad_id", nullable = false)
	public long getRunadId() {
		return this.runadId;
	}

	public void setRunadId(long runadId) {
		this.runadId = runadId;
	}

	@Column(name = "postad_id", nullable = false)
	public long getPostadId() {
		return this.postadId;
	}

	public void setPostadId(long postadId) {
		this.postadId = postadId;
	}

	@Column(name = "buyad_id", nullable = false)
	public long getBuyadId() {
		return this.buyadId;
	}

	public void setBuyadId(long buyadId) {
		this.buyadId = buyadId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RunadId))
			return false;
		RunadId castOther = (RunadId) other;

		return (this.getRunadId() == castOther.getRunadId())
				&& (this.getPostadId() == castOther.getPostadId())
				&& (this.getBuyadId() == castOther.getBuyadId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRunadId();
		result = 37 * result + (int) this.getPostadId();
		result = 37 * result + (int) this.getBuyadId();
		return result;
	}

}
