package org.itri.ccma.tarsan.hibernate;
// Generated 2016/7/1 ¤W¤È 11:08:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SplashSchedule generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "splash_schedule")
public class SplashSchedule implements java.io.Serializable {

	private long splashScheduleId;
	private Date scheduleTime;
	private String pageUrl;
	private String userId;
	private Date updateTime;
	private Date createTime;
	private boolean del;

	public SplashSchedule() {
	}

	public SplashSchedule(long splashScheduleId, boolean del) {
		this.splashScheduleId = splashScheduleId;
		this.del = del;
	}

	public SplashSchedule(long splashScheduleId, Date scheduleTime,
			String pageUrl, String userId, Date updateTime, Date createTime,
			boolean del) {
		this.splashScheduleId = splashScheduleId;
		this.scheduleTime = scheduleTime;
		this.pageUrl = pageUrl;
		this.userId = userId;
		this.updateTime = updateTime;
		this.createTime = createTime;
		this.del = del;
	}
	@SequenceGenerator(name="splash_schedule_seq", sequenceName="splash_schedule_splash_schedule_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="splash_schedule_seq")
	@Id

	@Column(name = "splash_schedule_id", unique = true, nullable = false)
	public long getSplashScheduleId() {
		return this.splashScheduleId;
	}

	public void setSplashScheduleId(long splashScheduleId) {
		this.splashScheduleId = splashScheduleId;
	}
	@Column(name = "schedule_time", length=29)
	public Date getScheduleTime() {
		return this.scheduleTime;
	}

	public void setScheduleTime(Date scheduleTime) {
		this.scheduleTime = scheduleTime;
	}
	@Column(name = "page_url", length=65535)
	public String getPageUrl() {
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}
	@Column(name = "user_id", length=128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	@Column(name = "update_time", length=29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	@Column(name = "create_time", length=29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}	
	@Column(name = "del", nullable = false)
	public boolean isDel() {
		return this.del;
	}

	public void setDel(boolean del) {
		this.del = del;
	}

}
