package org.itri.ccma.tarsan.hibernate;
// Generated Sep 3, 2015 11:03:17 AM by Hibernate Tools 4.3.1
import com.fasterxml.jackson.annotation.JsonIgnore;import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userevent generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "userevent")
public class Userevent implements java.io.Serializable {

	private long usereventId;
	private Pattern pattern;
	private Users users;
	private String searchKeyword;
	private Date createdDateTime;
	private String urlHost;
	private String urlPath;
	private String sessionId;
	private String ip;
	private Boolean productSearchFlag;
	private String urlReferer;
	private Long parentId;
	private Long rootId;

	public Userevent() {
	}

	public Userevent(long usereventId, Date createdDateTime) {
		this.usereventId = usereventId;
		this.createdDateTime = createdDateTime;
	}

	public Userevent(long usereventId, Pattern pattern, Users users, String searchKeyword, Date createdDateTime,
			String urlHost, String urlPath, String sessionId, String ip, Boolean productSearchFlag, String urlReferer,
			Long parentId, Long rootId) {
		this.usereventId = usereventId;
		this.pattern = pattern;
		this.users = users;
		this.searchKeyword = searchKeyword;
		this.createdDateTime = createdDateTime;
		this.urlHost = urlHost;
		this.urlPath = urlPath;
		this.sessionId = sessionId;
		this.ip = ip;
		this.productSearchFlag = productSearchFlag;
		this.urlReferer = urlReferer;
		this.parentId = parentId;
		this.rootId = rootId;
	}

	@SequenceGenerator(name="userevent_seq", sequenceName="userevent_userevent_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="userevent_seq")	@Id

	@Column(name = "userevent_id", unique = true, nullable = false)
	public long getUsereventId() {
		return this.usereventId;
	}

	public void setUsereventId(long usereventId) {
		this.usereventId = usereventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pattern_id")
	@JsonIgnore	public Pattern getPattern() {
		return this.pattern;
	}

	public void setPattern(Pattern pattern) {
		this.pattern = pattern;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id")
	@JsonIgnore	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "search_keyword", length = 512)
	public String getSearchKeyword() {
		return this.searchKeyword;
	}

	public void setSearchKeyword(String searchKeyword) {
		this.searchKeyword = searchKeyword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date_time", nullable = false, length = 29)
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "url_host", length = 128)
	public String getUrlHost() {
		return this.urlHost;
	}

	public void setUrlHost(String urlHost) {
		this.urlHost = urlHost;
	}

	@Column(name = "url_path", length = 2048)
	public String getUrlPath() {
		return this.urlPath;
	}

	public void setUrlPath(String urlPath) {
		this.urlPath = urlPath;
	}

	@Column(name = "session_id", length = 128)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "ip", length = 64)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "product_search_flag")
	public Boolean getProductSearchFlag() {
		return this.productSearchFlag;
	}

	public void setProductSearchFlag(Boolean productSearchFlag) {
		this.productSearchFlag = productSearchFlag;
	}

	@Column(name = "url_referer", length = 2048)
	public String getUrlReferer() {
		return this.urlReferer;
	}

	public void setUrlReferer(String urlReferer) {
		this.urlReferer = urlReferer;
	}

	@Column(name = "parent_id")
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "root_id")
	public Long getRootId() {
		return this.rootId;
	}

	public void setRootId(Long rootId) {
		this.rootId = rootId;
	}

}
