package org.itri.ccma.tarsan.hibernate;
// Generated Sep 3, 2015 11:03:17 AM by Hibernate Tools 4.3.1
import javax.persistence.GeneratedValue;import javax.persistence.SequenceGenerator;import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WebType generated by hbm2java
 */
@SuppressWarnings("serial")@Entity
@Table(name = "web_type")
public class WebType implements java.io.Serializable {

	private long webTypeId;
	private String name;
	private String remarks;

	public WebType() {
	}

	public WebType(long webTypeId, String name) {
		this.webTypeId = webTypeId;
		this.name = name;
	}

	public WebType(long webTypeId, String name, String remarks) {
		this.webTypeId = webTypeId;
		this.name = name;
		this.remarks = remarks;
	}

	@SequenceGenerator(name="web_type_seq", sequenceName="web_type_web_type_id_seq", allocationSize=1)	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="web_type_seq")	@Id

	@Column(name = "web_type_id", unique = true, nullable = false)
	public long getWebTypeId() {
		return this.webTypeId;
	}

	public void setWebTypeId(long webTypeId) {
		this.webTypeId = webTypeId;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "remarks", length = 512)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
